spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shoppingmall_test?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root # 진짜 user로 썼다가 1시간 개삽질해서 죽일뻔
    password: "dnjswhdals1@"


  jpa:
    # database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        storage_engine: innodb

    hibernate:
      ddl-auto: update # 애플리케이션 실행시점에 가지고 있는 엔티티를 전부 지우고 다시 추가해줌.(?)

#    properties:
#      hibernate:
#        #default_batch_fetch_size: 100
#        #          show_sql: true #system.out을 통해 출력함
#        format_sql: true
